import type { CaseType } from '../src'

export const CASE_FIXTURES: Record<CaseType, string> = {
  CONSTANT_CASE: 'HELLO_WORLD',
  'Capital Case': 'Hello World',
  PascalCase: 'HelloWorld',
  Pascal_Snake_Case: 'Hello_World',
  'Sentence case': 'Hello world',
  'Train-Case': 'Hello-World',
  camelCase: 'helloWorld',
  capitalCase: 'Hello World',
  constantCase: 'HELLO_WORLD',
  'dot.case': 'hello.world',
  dotCase: 'hello.world',
  'kebab-case': 'hello-world',
  kebabCase: 'hello-world',
  'no case': 'hello world',
  noCase: 'hello world',
  pascalCase: 'HelloWorld',
  pascalSnakeCase: 'Hello_World',
  'path/case': 'hello/world',
  pathCase: 'hello/world',
  sentenceCase: 'Hello world',
  snakeCase: 'hello_world',
  snake_case: 'hello_world',
  trainCase: 'Hello-World',
}
