import type { CaseType } from '../src'

export const CASE_FIXTURES: Record<CaseType, string> = {
  CONSTANT_CASE: 'CONSTANT_CASE',
  'Capital Case': 'Capital Case',
  PascalCase: 'PascalCase',
  Pascal_Snake_Case: 'Pascal_Snake_Case',
  'Sentence case': 'Sentence case',
  'Train-Case': 'Train-Case',
  camelCase: 'camelCase',
  capitalCase: 'Capital Case',
  constantCase: 'CONSTANT_CASE',
  'dot.case': 'dot.case',
  dotCase: 'dot.case',
  'kebab-case': 'kebab-case',
  kebabCase: 'kebab-case',
  'no case': 'no case',
  noCase: 'no case',
  pascalCase: 'PascalCase',
  pascalSnakeCase: 'Pascal_Snake_Case',
  'path/case': 'path/case',
  pathCase: 'path/case',
  sentenceCase: 'Sentence case',
  snakeCase: 'snake_case',
  snake_case: 'snake_case',
  trainCase: 'Train-Case',
}
